cartpole:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100 

  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: slider_to_cart
    pid: {p: 100.0, i: 0.01, d: 5.0}
  
  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: cart_to_pole
    pid: {p: 100, i: 0.01, d: 5.0}